# Generated by Django 5.1.2 on 2024-10-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_user_name_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_method', models.CharField(max_length=20)),
                ('details', models.JSONField()),
                ('users', models.ManyToManyField(to='expenses.user')),
            ],
        ),
    ]
