# Generated by Django 5.1.2 on 2024-10-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
